### ISSUE TITLE
Create a frontend / fullstack project

### ISSUE THREAD

**Issue by gourav221b** [dsc-tiu/WebDev2021-22#2]

**Comment by Mustafa-Azad025** [comment]
Hey @gourav221b ,
Will You Provide Some More Details On Issue. This Is My Field Of Interest and I Want To Contribute.

**Comment by Manthan-Kuber** [comment]
Hello I am interested to work on the same. I already have a few ready. So I have to send a PR for the same after 1st October right?
Can you assign the issue to me ?

**Comment by gourav221b** [comment]
This issue is open to all and doesnt need to be assigned to anyone. Yes we'll merge the PRs from 1st oct. It'll be better if you could provide a demo link with it

**Comment by Manthan-Kuber** [comment]
> This issue is open to all and doesnt need to be assigned to anyone. Yes we'll merge the PRs from 1st oct. It'll be better if you could provide a demo link with it

Alright

**Comment by Mustafa-Azad025** [comment]
> This issue is open to all and doesnt need to be assigned to anyone. Yes we'll merge the PRs from 1st oct. It'll be better if you could provide a demo link with it

will frontend will be of any type or have some conditions.

**Comment by gourav221b** [comment]
> > This issue is open to all and doesnt need to be assigned to anyone. Yes we'll merge the PRs from 1st oct. It'll be better if you could provide a demo link with it
> 
> will frontend will be of any type or have some conditions.

i request you to provide your best work and ensure its your own original work and not a copy paste

**Comment by Manthan-Kuber** [comment]
@gourav221b  This is a todo app I created a few months back. https://manthan-kuber.github.io/todo-app/
You may check it out. If this is good to go, I'll raise a PR on Oct 1st
